title: JLawman.com
author: Josh Lawman
email: jlawman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Python for Data Science

twitter_username: JoshLawman
github_username:  jlawman

category-list: [pandas, sklearn, deep-learning]

sass:
    style: compressed